name: rolarm_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  bottom_navy_bar: ^6.0.0
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.5
  flutter_joystick: ^0.0.3
  firebase_core: ^2.9.0
  cloud_firestore: ^4.4.4
  date_time_picker: ^2.1.0
  bot_toast: ^4.0.3
  intl: ^0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

